### ISSUE TITLE
Whoops! rex_sql_exception

### ISSUE THREAD

**Issue by AnnikaL123** [TobiasKrais/d2u_jobs#1]
Ich bekomme das AddOn nicht zum Laufen. Installiert, Job angelegt, soweit ok. Der Jobname wird in der Liste nicht angezeigt. Löschen und neue Jobs anlegen geht, aber beim Versuch, den Job zu bearbeiten kommt

"rex_sql_exception
Error while executing statement "SELECT * FROM rex_d2u_jobs_jobs AS jobs LEFT JOIN rex_d2u_jobs_jobs_lang AS lang ON jobs.job_id = lang.job_id WHERE jobs.job_id = 2 AND clang_id = "! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

...redaxo/src/core/lib/sql/sql.php"

Das installierte Modul liefert auch keine Ausgabe.
Aktuell unter redaxo 5.5.1 und d2u 1.0.2.

**Comment by TobiasKrais** [comment]
Das sieht nicht gut aus. Kommt der Fehler in der aktuellen Entwicklerversion die du von Github ziehen kannst ebenfalls vor?

Ich brauche mehr Infos: kannst du einen Screenshot des gesamten Fehlers posten. In der Fehlermeldung steht der Stack Trace mit dem Hinweis in welcher der Dateien des Addons der Fehler aufkommt. Danke vorab!

**Comment by TobiasKrais** [comment]
Ach so, noch was: hast du die Einstellungen im D2U Helper Addon vorgenommen?

**Comment by TobiasKrais** [comment]
Danke für deine schnelle Antwort. Wenn ich das richtig sehe hast du das HR4You Plugin installiert. Hast du die Einstellungen des Addons nach der Installation des Addons angepasst? Falls nein, hole das bitte nach.

Außerdem habe ich gerade eben einen commit gemacht, der das Problem beheben sollte, wenn die Einstellungen noch nicht gesetzt sind.

**Comment by AnnikaL123** [comment]
Du meinst das HR4You_import? Das wurde mit heruntergeladen, aber nicht installiert.
Die jobs.php habe ich mir gezogen. Jetzt kann ich auf "editieren" klicke und habe dann einen leeren Datensatz. Bearbeite ich diesen leeren Datensatz, wird der Job gespeichert und richtig angezeigt (Backend wie Frontend, bis auf das Error beim Bild im FE)

**Comment by TobiasKrais** [comment]
OK. Danke, dass du so fix bist! Das ist seltsam. Wie viele Sprachen hast du am Start? Hast du für jede Sprache eine Übersetzung eingegeben?

Welches Bild im Frontend erzeugt einen Fehler? Hast du da eventuell auch einen Screenshot?

**Comment by AnnikaL123** [comment]
Es ist keine (zusätzliche) Sprache angelegt. Ein Bild ist auch nicht zugewiesen, evtl. wird da nur das Vorschaubild nicht gefunden. Kann der Medienmanager Pfadangaben? 

<img src="index.php?rex_media_type=640x249&amp;rex_media_file=/assets/addons/d2u_jobs/noavatar.jpg" alt="test1234">

Ich muss jetzt leider los, bin dir sehr dankbar für deine Mühe!

**Comment by TobiasKrais** [comment]
Jetzt habe ich den Fehler gefunden und behoben. Außerdem auch das Modula angepasst, so dass das mit dem Bild auch besser funktioniert. Eventuell musst du noch die in den Jobs gespeicherte Bilder korrigieren, wenn der noavatar.jpg dort drin ist. Dann lösche ihn einfach raus.

Gerade eben habe ich Version 1.0.3 veröffentlicht. Einfach per Installer aktualisieren und es sollte funktionieren. Danke für deine Fehlermeldungen!
