### ISSUE TITLE
Fehlende Sprog-Platzhalter

### ISSUE THREAD

**Issue by thielpeter** [TobiasKrais/d2u_jobs#4]
Kann es sein das manche Platzhalter wie zbsp. "d2u_jobs_vacancies", "d2u_jobs_region" oder "d2u_jobs_reference_number" fehlen, oder ist das mit Absicht so und das soll man manuell nachtragen?

**Comment by TobiasKrais** [comment]
Die Platzhalter sind vorhanden. Hast du in den Einstellungen des Addons die Sprachzuweisungen gemacht? Dann sollten sie Platzhalter installiert werden.

**Comment by thielpeter** [comment]
Das Problem liegt darin, dass im Modul D2U Stellenmarkt - Stellenanzeigen Zeile 56/57 $sprog->getConfig('wildcard_open_tag') Null ergibt. Ich habe das wie folgt abgeändert:
```
$tag_open = $sprog->getConfig('wildcard_open_tag') ? $sprog->getConfig('wildcard_open_tag') : '{{';
$tag_close = $sprog->getConfig('wildcard_close_tag') ? $sprog->getConfig('wildcard_close_tag') : '}}';
```

**Comment by TobiasKrais** [comment]
Ah, ich glaube das kenne ich. Bist du in der Installation schon mal in die Einstellungen des Sprog Addons gegangen und hast sie gespeichert? Also auch, wenn du keine Änderungen der Einstellungen vorgenommen hast? Tritt danach der Fehler immernoch auf?

**Comment by thielpeter** [comment]
Nein dann ist der Fehler weg 👍

**Comment by TobiasKrais** [comment]
Das ist ja schon interessant. Kannst du bitte diese Erfahrung in den Issue von Sprog rein schreiben? Vielleicht wird dem dann noch Beachtung geschenkt.
