### ISSUE TITLE
Fehler Job erstellen

### ISSUE THREAD

**Issue by thielpeter** [TobiasKrais/d2u_jobs#5]
Wenn ich einen Job erstelle und dann in "Texte in Sprache "deutsch" die Option "... ist zur Zeit nicht vorgesehen und soll nicht gespeichert werden" wähle, dann meckert er beim abspeichern "Eingaben wurden nicht gespeichert, da keine Sprachdaten ausgefüllt wurden.". Das sollte ja eigentlich nicht so sein, richtig?

**Comment by TobiasKrais** [comment]
Jain. Ohne sprachbezogene Daten kann man mit einem Job nichts anfangen. Aber dass dann gleich alle eingegebenen Daten verloren gehen ist unglücklich. Jetzt wird vorher per JavaScript geprüft, ob mindestens eine Sprache eingegeben wurde.
